ClassBoots/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClassBoots.Models;
using Microsoft.AspNetCore.Authorization;

namespace ClassBoots.Controllers
{
    [Authorize]
    public class SchoolController : Controller
    {
        private readonly ModelContext _context;

        public SchoolController(ModelContext context)
        {
            _context = context;
        }

        // GET: School
        public async Task<IActionResult> Index()
        {
            if (User.FindFirst("Role").Value == "Admin")
            {
                return View(await _context.School.ToListAsync());
            }
            else
                return NotFound("Access Dinied");
        }

        // GET: School/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (User.FindFirst("Role").Value == "Admin")
            {
                if (id == null)
                {
                    return NotFound();
                }

                var school = await _context.School
                    .FirstOrDefaultAsync(m => m.ID == id);
                if (school == null)
                {
                    return NotFound();
                }

                return View(school);
            }
            else
                return NotFound("Access Dinied");

        }

        // GET: School/Create
        public IActionResult Create()
        {

            if (User.FindFirst("Role").Value == "Admin")
            {
                return View();
            }
            else
                return NotFound("Access Dinied");
        }

        // POST: School/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,InstitutionID,Name")] School school)
        {

            if (User.FindFirst("Role").Value == "Admin")
            {
                if (ModelState.IsValid)
                {
                    _context.Add(school);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(school);
            }
            else
                return NotFound("Access Dinied");

        }

        // GET: School/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (User.FindFirst("Role").Value == "Admin")
            {

                if (id == null)
                {
                    return NotFound();
                }

                var school = await _context.School.FindAsync(id);
                if (school == null)
                {
                    return NotFound();
                }
                return View(school);
            }
            else
                return NotFound("Access Dinied");
        }

        // POST: School/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,InstitutionID,Name")] School school)
        {

            if (User.FindFirst("Role").Value == "Admin")
            {
                if (id != school.ID)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(school);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!SchoolExists(school.ID))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(school);
            }
            else
                return NotFound("Access Dinied");

        }

        // GET: School/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (User.FindFirst("Role").Value == "Admin")
            {
                if (id == null)
                {
                    return NotFound();
                }

                var school = await _context.School
                    .FirstOrDefaultAsync(m => m.ID == id);
                if (school == null)
                {
                    return NotFound();
                }

                return View(school);
            }
            else
                return NotFound("Access Dinied");

        }

        // POST: School/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (User.FindFirst("Role").Value == "Admin")
            {
                var school = await _context.School.FindAsync(id);
                _context.School.Remove(school);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
                return NotFound("Access Dinied");

        }

        private bool SchoolExists(int id)
        {

            if (User.FindFirst("Role").Value == "Admin")
            {
                return _context.School.Any(e => e.ID == id);
            }
            else
                return false;
        }
    }
}

ClassBoots/Controllers/VideoController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ClassBoots.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using ClassBoots.Areas.Identity.Data;
using Accord.MachineLearning.Rules;

namespace ClassBoots.Controllers
{
    [Authorize]
    public class VideoController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ModelContext _context;

        public VideoController(ModelContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Video
        public async Task<IActionResult> Index()
        {
            if (User.FindFirst("Role").Value == "Admin")
                return View(await _context.Video.ToListAsync());

            return NotFound("Access Dinied");
        }

        public async Task<IdentityResult> AddToUserHistory(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
                return null;
            string history = user.History;
            if (history == "" || history == null)
            {
                history = "" + id;
            }
            else
            {
                bool flag = false;
                List<string> historyList = history.Split(',').ToList();
                historyList.ForEach(x =>
                {
                    if ("" + id == x)
                        flag = true; // NIR?
                });

                if (!flag)
                    history += "," + id + "";
            }
            user.History = history;
            var result = await _userManager.UpdateAsync(user);
            return result;
        }

        // GET: Video/View/5 with full layout!
        public async Task<IActionResult> View(int? id)
        {

            if (id == null)
                return NotFound();

            var video = await _context.Video
                    .FirstOrDefaultAsync(m => m.ID == id);

            if (video == null)
                return NotFound();

            video.Views++;
            _context.Update(video);
            await AddToUserHistory(id);
            await _context.SaveChangesAsync();
            return View(video);
        }

        // GET: Video/Details/5 lightweight layout
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var video = await _context.Video
                    .FirstOrDefaultAsync(m => m.ID == id);
            video.Views++;
            _context.Update(video);
            await _context.SaveChangesAsync();
            if (video == null)
            {
                return NotFound();
            }
            await AddToUserHistory(id);
            return View(video);
        }

        // GET: Video/Create
        public IActionResult Create()
        {
            if (User.FindFirst("Role").Value != null)
                return View();
            return NotFound("Access Dinied");
        }

        // POST: Video/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,LectureID,URL,Views,Position,OwnerID")] Video video)
        {
            char[] videoURL = video.URL.ToArray();
            string videoID = "";
            for (int i = 0; i < videoURL.Length - 2; i++)
            {
                if (videoURL[i] == 'v' && videoURL[i + 1] == '=')
                {
                    for (int j = i + 2; j < i + 13; j++)
                    {
                        videoID += video.URL[j];
                    }
                    break;
                }
            }
            if (videoID != "")
            {
                video.URL = videoID;
                if (ModelState.IsValid)
                {
                    video.OwnerID = User.FindFirst(ClaimTypes.Name).Value;
                    _context.Add(video);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(video);
            }
            return NotFound("Video link broke.");
        }

        // GET: Video/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var video = await _context.Video.FindAsync(id);
            if (User.FindFirst("Role").Value == "Admin" || video.OwnerID == User.FindFirst(ClaimTypes.Name).Value)
            {
                if (video == null || id == null)
                    return NotFound();

                return View(video);
            }
            return NotFound("Access Dinied");

        }

        // POST: Video/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,LectureID,URL,Views,Position,OwnerID")] Video video)
        {
            if (User.FindFirst("Role").Value == "Admin" || video.OwnerID == User.FindFirst(ClaimTypes.Name).Value)
            {
                if (id != video.ID)
                {
                    return NotFound();
                }
                var oldVideo = _context.Video.Find(id);
                if (oldVideo != null)
                {
                    oldVideo.Name = video.Name;
                    oldVideo.URL = video.URL;
                    oldVideo.Position = video.Position;
                }
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(oldVideo);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!VideoExists(video.ID))
                            return NotFound();
                        else
                            throw; // ILUZ?
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(video);
            }
            return NotFound("Access Dinied");
        }

        // GET: Video/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var video = await _context.Video
    .FirstOrDefaultAsync(m => m.ID == id);
            if (User.FindFirst("Role").Value == "Admin" || video.OwnerID == User.FindFirst(ClaimTypes.Name).Value)
            {
                if (video == null || id == null)
                    return NotFound();

                return View(video);
            }

            return NotFound("Access Dinied");
        }

        // POST: Video/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var video = await _context.Video.FindAsync(id);
            if (User.FindFirst("Role").Value == "Admin" || video.OwnerID == User.FindFirst(ClaimTypes.Name).Value)
            {
                _context.Video.Remove(video);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return NotFound("Access Dinied");
        }

        private bool VideoExists(int id)
        {
            return _context.Video.Any(e => e.ID == id);
        }

        public AssociationRuleMatcher<int> CreateAprioriClassifier()
        {
            // Create a new a-priori learning algorithm with support 3
            Apriori apriori = new Apriori(threshold: 2, confidence: 0);

            int[][] histories = GetAllViewingHistories();

            // Use the algorithm to learn a set matcher
            AssociationRuleMatcher<int> classifier = apriori.Learn(histories);

            return classifier;
        }

        [HttpGet("learn/{videoIDS}/{limit?}")]
        public List<Video> GetRelatedVideos([FromRoute] int[] videoIDS,[FromRoute] int limit = 5)
        {
            AssociationRuleMatcher<int> classifier = CreateAprioriClassifier();

            // Get the videos that appear most with the video who's ID is the given argument videoID
            int[][] matches = classifier.Decide(videoIDS);
            List<Video> videos = new List<Video>();
            HashSet<int> ids = new HashSet<int>();

            // Merge all the video IDs into a single HashSet, this will remove duplicates.
            foreach (int[] e in matches)
                foreach (int f in e)
                    ids.Add(f);
                
            // Take only the given amount of videos from the argument 'limit'.
           ids = ids.Take(limit).ToHashSet();

            // Get the full video model for each of the IDs.
            foreach (int id in ids)
                videos.Add(_context.Video.FirstOrDefault(video => video.ID == id));

            return videos;
        }

        public int[][] GetAllViewingHistories()
        {
            List<User> users = _userManager.Users.ToList();
            List<int[]> histories = new List<int[]>();
            users.ForEach(user =>
            {
                if(user.History != "" && user.History != null)
                    histories.Add(user.History.Split(',').Select(int.Parse).ToArray());
            });

            return histories.ToArray();
        }


    }
}

ClassBoots/Views/Shared/_Empty.cshtml
@RenderBody()
@RenderSection("Scripts", required: false)

ClassBoots/Views/Shared/_Layout-Default.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClassBoots</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ClassBoots</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Administrator" asp-action="Statistics">Statistics</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ClassBoots</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ClassBoots/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/assets/images/favicon.png">
    <title>@ViewData["Title"] - ClassBoots</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- chartist CSS -->
    <link href="~/assets/plugins/chartist-js/dist/chartist.min.css" rel="stylesheet">
    <link href="~/assets/plugins/chartist-js/dist/chartist-init.css" rel="stylesheet">
    <link href="~/assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css" rel="stylesheet">
    <!--This page css - Morris CSS -->
    <link href="~/assets/plugins/c3-master/c3.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="~/css/colors/blue.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    </head>

<body class="fix-header fix-sidebar">
    <div class="preloader">

        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <aside class="left-sidebar" style="padding-top:unset;">
        <a href="/" alt="ClassBoots Home Page"> <div class="logo-classboots light-logo"></div></a>

        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <li>
                        <a class="waves-effect waves-dark" asp-area="" asp-controller="Administrator" asp-action="Index" aria-expanded="false"><i class="mdi mdi-home"></i><span class="hide-menu">Index </span></a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" asp-area="" asp-controller="Administrator" asp-action="Statistics" aria-expanded="false"><i class="mdi mdi-chart-bar"></i><span class="hide-menu">Statistics</span></a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" asp-area="" asp-controller="Administrator" asp-action="Users" aria-expanded="false"><i class="mdi mdi-account-multiple"></i><span class="hide-menu">User</span></a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" asp-area="" asp-controller="Lecturer" asp-action="Index" aria-expanded="false"><i class="mdi mdi-glasses"></i><span class="hide-menu">Lecturers</span></a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" asp-area="" asp-controller="Institution" asp-action="Index" aria-expanded="false"><i class="mdi mdi-school"></i><span class="hide-menu">Institutions</span></a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" asp-area="" asp-controller="School" asp-action="Index" aria-expanded="false"><i class="mdi mdi-domain"></i><span class="hide-menu">Schools</span></a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" asp-area="" asp-controller="Subject" asp-action="Index" aria-expanded="false"><i class="mdi mdi-file-multiple"></i><span class="hide-menu">Subjects</span></a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" asp-area="" asp-controller="Lecture" asp-action="Index" aria-expanded="false"><i class="mdi mdi-format-list-numbers"></i><span class="hide-menu">Lectures</span></a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" asp-area="" asp-controller="Video" asp-action="Index" aria-expanded="false"><i class="mdi mdi-video"></i><span class="hide-menu">Videos</span></a>
                    </li>
                </ul>
                <div class="text-center m-t-30">
                    <a a asp-area="" asp-controller="Home" asp-action="Index" class="btn waves-effect waves-light btn-warning hidden-md-down">FRONTEND</a>
                </div>
            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->

    </aside>
    <!-- ============================================================== -->
    <!-- End Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->

    <div class="page-wrapper">

        <div class="container-fluid">
            <!-- ============================================================== --
            <div class="row page-titles">
                <partial name="_CookieConsentPartial" />
                <div id="path"></div>
                <div id="results">You can start search</div>
            </div>
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>

	<footer class="footer">
		<div class="home-circle">
			<div class="class-boots-home-icon"></div>
		</div>
		<br />
		@ViewData["Title"]
	</footer>

    <environment include="Development">
        <script src="~/assets/plugins/jquery/jquery.js"></script>
        <script src="~/assets/plugins/bootstrap/js/tether.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/jquery.slimscroll.js"></script>
        <script src="~/js/waves.js"></script>
        <script src="~/js/sidebarmenu.js"></script>
        <script src="~/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
        <script src="~/js/custom.min.js"></script>
        <script src="~/js/jquery.session.js"></script>


    </environment>
    <environment exclude="Development">
        <script src="~/assets/plugins/jquery/jquery.js"></script>
        <script src="~/assets/plugins/bootstrap/js/tether.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/jquery.slimscroll.js"></script>
        <script src="~/js/waves.js"></script>
        <script src="~/js/sidebarmenu.js"></script>
        <script src="~/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
        <script src="~/js/custom.min.js"></script>
        <script src="~/js/jquery.session.js"></script>

    </environment>



    @RenderSection("Scripts", required: false)

</body>
</html>

ClassBoots/Views/Shared/_LeftSidebar.cshtml
@using Microsoft.AspNetCore.Identity
@using ClassBoots.Areas.Identity.Data
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!-- Defaults -->
<li id="menuitem"><a class="waves-effect waves-dark" aria-expanded="false"><img class="bg-white little-margin thumb-md img-circle" /><span class="hide-menu"></span></a></li>
<li style="width:50px;" id="previousbtn"><a class="waves-effect waves-dark" aria-expanded="false"><i class="mdi mdi-arrow-left-bold-circle"></i><span class="hide-menu"></span></a></li>
<li style="width:50px;" id="homebtn"><a class="waves-effect waves-dark" aria-expanded="false"><i class="mdi mdi-home"></i><span class="hide-menu"></span></a></li>

<button id="circlebtn" class="btn btn-circle btn-lg btn-success waves-effect waves-dark">+</button>

<aside class="left-sidebar">
    <div><!-- <partial name="_LoginPartial" /> --></div>
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav"></ul>
        </nav>

        @if (SignInManager.IsSignedIn(User) && User.FindFirst("Role").Value == "Admin")
        {
            <div class="text-center m-t-30">
                <a asp-area="" asp-controller="Administrator" asp-action="Index" class="btn waves-effect waves-light btn-warning hidden-md-down">BACKEND</a>
            </div>
        }
        <!-- End Sidebar navigation -->

    </div>
    <!-- End Sidebar scroll-->
    <!-- Bottom points-->
    <div class="sidebar-footer">
        <div id="sidebarnav-options">
        </div>
        <partial name="_Login-nav" />
    </div>
    <!-- End Bottom points-->
</aside>

ClassBoots/Views/Shared/_Login-nav.cshtml
@using Microsoft.AspNetCore.Identity
@using ClassBoots.Areas.Identity.Data

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@if (SignInManager.IsSignedIn(User))
{
    
    <!-- item--><a href="/Identity/Account/Manage" class="link" data-toggle="tooltip" title="Settings"><i class="ti-settings"></i></a>
    <!-- item--><a href="" class="link" data-toggle="tooltip" title="Email"><i class="mdi mdi-gmail"></i></a>
    <!-- item--><a style="cursor:pointer" id="logout" class="link" data-toggle="tooltip" title="Logout"><i class="mdi mdi-power"></i></a>
    <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" method="post" id="logoutForm" class="navbar-right"></form>

}
else
{
}

ClassBoots/Views/Shared/_Naked.cshtml
@RenderBody()
@RenderSection("Scripts", required: false)

ClassBoots/Views/Shared/_Personal-area.cshtml
@using Microsoft.AspNetCore.Identity
@using ClassBoots.Areas.Identity.Data


@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item dropdown">
        <a id="nameArea" class="nav-link dropdown-toggle text-muted waves-effect waves-dark personal-name" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage" aria-haspopup="true" aria-expanded="false">@UserManager.GetUserName(User)</a>
    </li>
}
else
{
        <a class="loginlink" asp-area="Identity" asp-page="/Account/Login">Login</a>
}